### ISSUE TITLE
pyodide.asm.js:10 Pyodide has suffered a fatal error.

### ISSUE THREAD

**Issue by vinnividivicci** [IfcOpenShell/wasm-preview#1]
Hello,

I'm super excited to see IfcOpenShell come to the browser! I tried the [preview ](https://ifcopenshell.github.io/wasm-preview/) immediately but I keep getting this error (with any IFC):
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/591242/200580495-0f0caa83-b085-4b8b-bd68-3c110bbb0763.png">

Tried it in Edge & Chrome with the same result (with a couple of different ifc files.

I'm looking forward to being able to do IFC authoring in the browser 😄

**Comment by aothms** [comment]
I've seen the same on many trivial files. It's a bit strange, because any occt exception such as Standard_NoSuchObject should be caught in IfcOpenShell. My plan is to patch OCCT before building so that their exceptions inherit from std::exception so that at least pyodide can meaningfully process them and then we can see what the actual cause is.

**Comment by aothms** [comment]
With a bit more care this particular NoSuchObject error is not thrown in C++ anymore so often. So a couple trivial models now load for me. I'm not sure whether this is a reason to be reassured, there is still a fundamental question why this (and therefore which others) exception was not caught by ifcopenshell itself as is the case when compiling for cpython. Emscripten related compiler flags such as -fexceptions didn't seem to make a difference. Curious to hear your findings.

**Comment by vinnividivicci** [comment]
Thanks for looking into this! I can confirm that it works for me now, no more fatal crashes. I ran 3 real-world models through it and although it took very long to process and open (I know that's a known limitation for now), it eventually opened the models and things looked accurate. 

Really excited for the potential of this!
