### ISSUE TITLE
Download IFC from html/js

### ISSUE THREAD

**Issue by keshavanarayan** [IfcOpenShell/wasm-preview#7]
Hi @Moult @aothms,

I saw the previous issue on making downloading the IFC generated possible. It is a great place to start.
While you could get to it, I thought of giving it a shot myself. So in the "model.py" file, I have added this snippet.

![image](https://user-images.githubusercontent.com/74804559/229261916-9abcc64d-c255-4e5b-a07f-b7b27652c2bd.png)

And in the "draw_wall_on_click.html", I have added this snippet.
![image](https://user-images.githubusercontent.com/74804559/229261939-451c96d3-20d5-4c60-ba7b-e8d1f9741c96.png)
I thought it should work. But it does not. And neither it is showing any errors. 

How do I proceed with this?

**Comment by aothms** [comment]
CC @vinnividivicci 

What is `filename` in:

>     self.model.write(filename)

I don't think there would be an easy way to trigger the download by writing from pyodide. Rather we would need to get the string representation of the file using `return self.model.to_string()`. To trigger the download the solution today seems to be to generate a `<a>` with data URL. https://stackoverflow.com/questions/3665115/how-to-create-a-file-in-memory-for-user-to-download-but-not-through-server

**Comment by vinnividivicci** [comment]
Hi @keshavanarayan,

@aothms suggestion works. I created a [quick video ](https://www.youtube.com/watch?v=zUzO_uVryI0) to show how to do it and also put the code [example here](https://github.com/IfcOpenShell/wasm-preview/blob/master/examples/3_create_basic_wall_and_download.html).

Hope that helps!
